// 'use client';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import ThemeRegistry from './ThemeRegistry';
const inter = Inter({ subsets: ['latin'] });

// export const metadata: Metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>{/* Metadata can go here */}</head>
      <body className={inter.className}>
        <ThemeRegistry>
          <header> this is the header </header>
          <main>{children}</main>
          <footer>this is the footer</footer>
        </ThemeRegistry>{' '}
      </body>
    </html>
  );
}
